---
- name: Implement Secure Network Segmentation with UFW
  hosts: controlnode1:controlnode2
  become: yes
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow incoming traffic on specific ports and IP addresses
      ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        from_ip: "{{ item.to_addr }}"
      loop:
        - { port: '22', proto: 'tcp', to_addr: '172.17.0.5/16' }
        - { port: '80', proto: 'tcp', to_addr: '172.17.0.6/16' }
        - { port: '443', proto: 'tcp', to_addr: '172.17.0.5/16' }

    - name: Test allowing incoming traffic FOR TESTING
      command: ufw status numbered | grep 'ALLOW' | grep 'in' || true
      register: allow_incoming_traffic
      ignore_errors: yes

    - name: Show allow incoming traffic result
      debug:
        var: allow_incoming_traffic.stdout_lines

    - name: Deny all incoming traffic
      ufw:
        rule: deny
        direction: in
        state: enabled

    - name: Test denying all incoming traffic FOR TESTING
      command: ufw status numbered | grep 'DENY' | grep 'in' || true
      register: deny_all_incoming_traffic
      ignore_errors: yes

    - name: Show deny all incoming traffic result
      debug:
        var: deny_all_incoming_traffic.stdout_lines

    - name: Test firewall rules FOR TESTING
      command: ufw status numbered
      register: ufw_status

    - name: Show firewall status
      debug:
        var: ufw_status.stdout_lines

    - name: Allow outgoing traffic
      ufw:
        rule: allow
        direction: out

    - name: Enable logging
      ufw:
        logging: yes
