---
- name: Install and Start Services
  hosts: controlnode1:controlnode2
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
  tasks:
    - name: Install gnupg package
      apt:
        name: gnupg
        state: present

    - name: Add Elasticsearch APT repository key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elasticsearch APT repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Install Kibana
      apt:
        name: kibana
        state: present

    - name: Install Logstash
      apt:
        name: logstash
        state: present

    - name: Install AIDE
      apt:
        name: aide
        state: present

    - name: Install Logwatch
      apt:
        name: logwatch
        state: present

    - name: Check Installation Status of Services
      shell: dpkg -l
      register: installed_packages

    - name: Print Installation Status
      debug:
        msg: |
          Elasticsearch: {% if installed_packages.stdout | regex_search('elasticsearch') %} Installed {% else %} Not Installed {% endif %}
          Prometheus: {% if installed_packages.stdout | regex_search('prometheus') %} Installed {% else %} Not Installed {% endif %}
          Fail2ban: {% if installed_packages.stdout | regex_search('fail2ban') %} Installed {% else %} Not Installed {% endif %}
          Kibana: {% if installed_packages.stdout | regex_search('kibana') %} Installed {% else %} Not Installed {% endif %}
          Logstash: {% if installed_packages.stdout | regex_search('logstash') %} Installed {% else %} Not Installed {% endif %}
          AIDE: {% if installed_packages.stdout | regex_search('aide') %} Installed {% else %} Not Installed {% endif %}
          Logwatch: {% if installed_packages.stdout | regex_search('logwatch') %} Installed {% else %} Not Installed {% endif %}
